### ISSUE TITLE
Edit page narrative

### ISSUE THREAD

**Issue by blackdotbug** [jacobdv/snuffleupagusses#64]
Remove "Team Snuffleupagusses"
Add attribution and links to data sources
Add methodology section/page
Add link to github repo
Add link to api homepage.

Expand the narrative explanation of the problem, and add narrative explanation of analysis and insights.

**Comment by etreznoski** [comment]
I'll tackle this portion!

**Comment by blackdotbug** [comment]
Excellent, Elizabeth. Go ahead and push some minimal change to your narrative branch and initiate a pull request and assign me as reviewer, please. :)

**Comment by blackdotbug** [comment]
how's this going?

**Comment by etreznoski** [comment]
It's going pretty good, I have some rough drafts going. I'm not sure on the formatting though. Should I leave the summary and analysis/conclusions at the top and then put the methodology and data sources at the bottom of the page?
I can have this ready to push by the end of the day.

**Comment by blackdotbug** [comment]
That sounds like a good plan, @etreznoski.

**Comment by etreznoski** [comment]
I pushed my changes.
