### ISSUE TITLE
add api homepage

### ISSUE THREAD

**Issue by blackdotbug** [jacobdv/snuffleupagusses#65]
add instructions page for api, with explanation of endpoints and examples of return data structure.

**Comment by pete6184** [comment]
I'll start on this. I might need a little clarification as to exactly what needs to be done but it sounds like something I can handle.

**Comment by blackdotbug** [comment]
Sounds good, Pete. Go ahead and create a branch for it and push it. Once there's anything to diff between your branch and main create a pull request and add me as a reviewer.

**Comment by pete6184** [comment]
I created the new branch. Just to clarify, I am making a new webpage that will link from the homepage to house the instructions, explanation, and examples.

**Comment by blackdotbug** [comment]
Ok, so you've got a flask app here with two routes defined for api endpoints already. Those return jsonified data from your database. 

You'll need to go into app.py and add a new route: 
```
# API Home route that displays api.html content.
@app.route("/api")
def index():
    return render_template("api.html")
```

And then add a new template to the templates folder called api.html where you'll build out the api instructions and examples.

**Comment by pete6184** [comment]
Got it. I pictured all that except the new app.py route. I have it created and am now working on the api.html page. Thank you for the direction.
