### ISSUE TITLE
create deployment branch for heroku

### ISSUE THREAD

**Issue by blackdotbug** [jacobdv/snuffleupagusses#69]
Once @mathewqpmiller has moved the database to the cloud, I think this task can safely be done.

**Comment by mathewqpmiller** [comment]
Sounds good

**Comment by mathewqpmiller** [comment]
I have created the Heroku app, invited collaborators and have transferred ownership to Jacob. Once he has accepted the invitation and assumed ownership of the app, the will be able to deploy the project in the "Deploy" tab by selecting "Deploy method - GitHub". There may be some administrative tasks after that.

**Comment by jacobdv** [comment]
I've connected heroku to this repo and I'll wait to deploy until we have a branch for that, but it should be all set to go at that point. I'll need the same MongoDB Atlas configuration variables as we'll need for the code itself but we should be set on the Heroku end pretty quickly.

**Comment by mathewqpmiller** [comment]
Deployment branch in GitHub has successfully been created. Heroku successfully connected to GitHub as well as the app was deployed. All team members have opened the app and found it to be in correct working order. There may need to be some aesthetic changes to the webpage, but as far as creating a deployment branch and deploying the app, this portion of the project is completed.
